DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS EventUser;
DROP TABLE IF EXISTS Photo;
DROP TABLE IF EXISTS Commentary;

CREATE TABLE Photo (
	id 		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	url 	TEXT NOT NULL
);

CREATE TABLE Commentary (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	idUser INTEGER NOT NULL,
	idEvent INTEGER	NOT NULL,
	commentDate DATE NOT NULL,
	commentary TEXT, 
	


	CONSTRAINT 	fk_idEvent FOREIGN KEY (idEvent) REFERENCES Event(id),
	CONSTRAINT fk_idUser FOREIGN KEY (idUser) REFERENCES User(id)
);

CREATE TABLE User (
	id				INTEGER	NOT NULL PRIMARY KEY AUTOINCREMENT,
	username		VARCHAR(64)	NOT NULL UNIQUE,
	email			VARCHAR(256) NOT NULL UNIQUE,
	password		VARCHAR(256) NOT NULL,
	idphoto 		INTEGER NOT NULL,
	fullname		TEXT NOT NULL,
	datanascimento	DATE
);


CREATE TABLE Event (
	id 			INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	idHost 		INTEGER NOT NULL REFERENCES User(id), 
	name		VARCHAR(32) NOT NULL,
	type		TEXT NOT NULL,
	description	TEXT,
	idPhoto 	INTEGER NOT NULL REFERENCES Photo(id),
	location 	TEXT NOT NULL,
	private		BOOLEAN	NOT NULL,
	creationDate DATE NOT NULL,
	eventDate 	DATE NOT NULL,
	CHECK((julianday(eventDate) - julianday(creationDate)) >= 0)
);

CREATE TABLE EventUser (
	idEvent INTEGER	NOT NULL,
	idUser INTEGER NOT NULL,

	CONSTRAINT 	pk_EventUser PRIMARY KEY (idUser, idEvent),
	CONSTRAINT 	fk_idEvent FOREIGN KEY (idEvent) REFERENCES Event(id),
	CONSTRAINT fk_idUser FOREIGN KEY (idUser) REFERENCES User(id)
);
