.bail ON
.mode columns
.headers on
.nullvalue NULL
PRAGMA foreign_keys = ON;

/*******INCLUDES********/
.read LTW_Database.sql
/***********************/


CREATE TRIGGER connectEventUser
	AFTER INSERT ON Event
	BEGIN
	INSERT INTO EventUser(idEvent, idUser) VALUES(New.id, New.idHost);
	END;

/*******INSERTS*********/
/*passwords: qwerty, 12345, asdasd*/
INSERT INTO Photo(URL) VALUES('../Resources/ProfilePics/defaultProfilePic.png');
INSERT INTO Photo(URL) VALUES('../Resources/ProfilePics/gustavo.jpg');
INSERT INTO Photo(URL) VALUES('../Resources/ProfilePics/eunasciaqui.png');
INSERT INTO Photo(URL) VALUES('../Resources/ProfilePics/carreira.png');

/*passwords: qwerty, 12345, asdasd*/
INSERT INTO User(USERNAME, FULLNAME, EMAIL, PASSWORD, DATANASCIMENTO, IDPHOTO) VALUES('Pigmoth', 'Daniel Silva Reis', 'pigmoth@gmail.com', '$2y$10$Pjnde6rRKvo4mDaQmWNYme1K6wqWbeoM/Asq6uGLMvqm4ms1eOqyq', '1995-01-03', 2); 
INSERT INTO User(USERNAME, FULLNAME, EMAIL, PASSWORD, DATANASCIMENTO, IDPHOTO) VALUES('guilhermevpinto', 'Guilherme Vieira Pinto', 'guilhermevpinto@gmail.com', '$2y$10$x7HX5nnwJaOhNfmEL5irx.dEnhmapRMzcS.76hC2H.dDTXmW8EpSG', '1994-12-13', 3);
INSERT INTO User(USERNAME, FULLNAME, EMAIL, PASSWORD, DATANASCIMENTO, IDPHOTO) VALUES('Nutil', 'Luis Ramos Pinto de Figueiredo', 'luisfigueiredos@hotmail.com', '$2y$10$ZOAtLO0TM04rgulbkuXcJO3AciQSc7blNs.ThNs81jUPm.uUuGNAu', '1995-04-20', 4);

INSERT INTO Location(NAME, ADDRESS, DESCRIPTION) VALUES('FEUP', 'Roberto Frias', 'FEUPCaffe Spot');
INSERT INTO Location(NAME, ADDRESS, DESCRIPTION) VALUES('Estacao de Comboio S. Bento', 'Aliados', 'Pouca Terra');
INSERT INTO Location(NAME, ADDRESS, DESCRIPTION) VALUES('Metro Sto. Ovidio', 'Sto. Ovidio', 'Terminal linha amarela');


/*eventos publicos*/
INSERT INTO Event(IDHOST,DESCRIPTION, IDPHOTO, IDLOCATION, PRIVATE, CREATIONDATE, EVENTDATE) VALUES(1,'Publico1', 1, 2, 0, '2015-11-16', '2015-11-17');
INSERT INTO Event(IDHOST,DESCRIPTION, IDPHOTO, IDLOCATION, PRIVATE, CREATIONDATE, EVENTDATE) VALUES(2,'Publico2', 1, 2, 0, '2015-11-16', '2015-11-17');
INSERT INTO Event(IDHOST,DESCRIPTION, IDPHOTO, IDLOCATION, PRIVATE, CREATIONDATE, EVENTDATE) VALUES(2,'Publico3', 1, 2, 0, '2015-11-16', '2015-11-17');
INSERT INTO Event(IDHOST,DESCRIPTION, IDPHOTO, IDLOCATION, PRIVATE, CREATIONDATE, EVENTDATE) VALUES(2,'Publico4', 1, 2, 0, '2015-11-16', '2015-11-17');
INSERT INTO Event(IDHOST,DESCRIPTION, IDPHOTO, IDLOCATION, PRIVATE, CREATIONDATE, EVENTDATE) VALUES(2,'Publico5', 1, 2, 0, '2015-11-16', '2015-11-17');
INSERT INTO Event(IDHOST,DESCRIPTION, IDPHOTO, IDLOCATION, PRIVATE, CREATIONDATE, EVENTDATE) VALUES(2,'Publico6', 1, 2, 0, '2015-11-16', '2015-11-17');
INSERT INTO Event(IDHOST,DESCRIPTION, IDPHOTO, IDLOCATION, PRIVATE, CREATIONDATE, EVENTDATE) VALUES(2,'Publico7', 1, 2, 0, '2015-11-16', '2015-11-17');

/*eventos privados*/
INSERT INTO Event(IDHOST,DESCRIPTION, IDPHOTO, IDLOCATION, PRIVATE, CREATIONDATE, EVENTDATE) VALUES(3,'Privado1', 2, 1, 1, '2015-11-10', '2015-11-14');
INSERT INTO Event(IDHOST,DESCRIPTION, IDPHOTO, IDLOCATION, PRIVATE, CREATIONDATE, EVENTDATE) VALUES(2,'Privado2', 1, 2, 1, '2015-11-16', '2015-11-17');
INSERT INTO Event(IDHOST,DESCRIPTION, IDPHOTO, IDLOCATION, PRIVATE, CREATIONDATE, EVENTDATE) VALUES(2,'Privado3', 1, 2, 1, '2015-11-16', '2015-11-17');
INSERT INTO Event(IDHOST,DESCRIPTION, IDPHOTO, IDLOCATION, PRIVATE, CREATIONDATE, EVENTDATE) VALUES(2,'Privado4', 1, 2, 1, '2015-11-16', '2015-11-17');

/*pigmoth*/
INSERT INTO EventUser(IDEVENT, IDUSER) VALUES(2, 1);
INSERT INTO EventUser(IDEVENT, IDUSER) VALUES(3, 1);
INSERT INTO EventUser(IDEVENT, IDUSER) VALUES(8, 1);
INSERT INTO EventUser(IDEVENT, IDUSER) VALUES(9, 1);

/*guilhermevpinto*/
INSERT INTO EventUser(IDEVENT, IDUSER) VALUES(1, 2);
INSERT INTO EventUser(IDEVENT, IDUSER) VALUES(8, 2);

/*Nutil*/
INSERT INTO EventUser(IDEVENT, IDUSER) VALUES(1, 3);
INSERT INTO EventUser(IDEVENT, IDUSER) VALUES(5, 3);
INSERT INTO EventUser(IDEVENT, IDUSER) VALUES(9, 3);
INSERT INTO EventUser(IDEVENT, IDUSER) VALUES(10, 3);