DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Photo;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS Location;


CREATE TABLE User (
	ID				INTEGER			NOT NULL		PRIMARY KEY 		AUTOINCREMENT,
	NAME			VARCHAR(256)	NOT NULL,
	MAIL			VARCHAR(256)	NOT NULL,
	VALIDATION 		BOOLEAN 		NOT NULL,
	DATANASCIMENTO	DATE,
	USERNAME		VARCHAR(64)		NOT NULL 		UNIQUE,
	PASSWORD		VARCHAR(64)		NOT NULL
);

CREATE TABLE Photo (
	ID 				INTEGER			NOT NULL		PRIMARY KEY 		AUTOINCREMENT,
	IDUSER			INTEGER			REFERENCES User(ID),
	UPLOADDATE		DATE 			NOT NULL,
	DESCRIPTION		TEXT
);

CREATE TABLE Location (
	ID 				INTEGER 		NOT NULL 		PRIMARY KEY 		AUTOINCREMENT,
	NAME			VARCHAR(64),
	ADDRESS 		VARCHAR(64)		NOT NULL,
	DESCRIPTION 	TEXT
);

CREATE TABLE Event (
	ID 				INTEGER 		NOT NULL 		PRIMARY KEY 		AUTOINCREMENT,
	IDUSER 			INTEGER 		NOT NULL 		REFERENCES User(ID),
	IDPHOTO			INTEGER 		NOT NULL 		REFERENCES Photo(ID),
	IDLOCATION 		INTEGER 		NOT NULL 		REFERENCES Location(ID),
	PRIVATE			BOOLEAN			NOT NULL,
	CREATIONDATE	DATE 			NOT NULL,
	EVENTDATE 		DATE 			NOT NULL,
	CHECK((julianday(EVENTDATE) - julianday(CREATIONDATE)) >= 0)
);